## Numpy Array Operations

1) np.concatenate()

In [3]:
import numpy as np

In [4]:
w1 = np.array([12,13,14,15])
w2 = np.array([18,19,20,21,22])
print(w1)
print(w2)

[12 13 14 15]
[18 19 20 21 22]


In [7]:
r1 = np.concatenate([w1,w2])
print(r1)
r2 = np.concatenate([w2,w1])
print(r2)

[12 13 14 15 18 19 20 21 22]
[18 19 20 21 22 12 13 14 15]


In [9]:
d1 = np.array([[1,2,3],[4,5,6]])
d2 = np.array([[7,8,9],[10,11,13]])
print(d1)
print(d2)
print(d1.shape, d2.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 13]]
(2, 3) (2, 3)


In [11]:
r2 = np.concatenate([d1,d2],axis=0) # column wise ( c wise concatenate)
# no new c are created, rather new r are created
print(r2)
r3 = np.concatenate([d1,d2]) # row wise ( r wise concatenate)
# no new r are created, rather new c are created
print(r3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]


2) np.vstack and np.hstack()

Vertically and horizontally

In [13]:
z1 = np.array([[1,2,3],[4,5,6]])
z2 = np.array([[-4,-2,0],[7,9,2]])
print(z1)
print(z2)

[[1 2 3]
 [4 5 6]]
[[-4 -2  0]
 [ 7  9  2]]


In [15]:
r1 = np.hstack((z1,z2))
#no new r are created, rather new c are created
r2 = np.vstack([z1,z2])
# no new c are created, rather new r are created
print(r1)
print(r2)

[[ 1  2  3 -4 -2  0]
 [ 4  5  6  7  9  2]]
[[ 1  2  3]
 [ 4  5  6]
 [-4 -2  0]
 [ 7  9  2]]


3) np.hsplit() and np.vsplit()

horizontally = c wise 
vertically = r wise

In [17]:
t = np.arange(1,9)
print(t)
res = np.hsplit(t,2)
print(res)

[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
w1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(w1)