Numpy Array Operations

Numpy provides different  functions for performing different array operations

In [2]:
import numpy as np

1) np.sum()

In [6]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.dtype)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2]
 [3 4]]
int32
4
(2, 2)
2


In [10]:
print(a)
print(a.sum())  # 1+2+3+4 = 10
print(a.sum(axis=1)) # axis = 1 (row wise) , 1+2 = 3, 3+4 = 7
print(a.sum(axis=0))  # axis = 0 (column wise) , 1+3 =4, 2+4 = 6

[[1 2]
 [3 4]]
10
[3 7]
[4 6]


In [12]:
b = np.arange(10,22).reshape(3,4)
print(b)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [14]:
print(b.sum()) # 10+11+....21 = 186
print(a.sum(axis=1)) # (row wise) , 10+11+12+13 = 46.....
print(a.sum(axis=0)) # column wise , 10+14+18 =42

186
[3 7]
[4 6]


2) np.min() and np.max()

In [16]:
m = [[ 12,13,4],[15,17,16],[18,19,11],[16,22,20]]
w1 = np.array(m)   # creating np.array out of list of list
print(w1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [22]:
# axis = 1 => row
# axis = 0 => Column

print(np.min(w1,axis=0))
print(np.min(w1,axis=1))
print(np.max(w1,axis=0))
print(np.max(w1,axis=1))

[12 13  4]
[ 4 15 11 16]
[18 22 20]
[13 17 19 22]


3) np.argmax() and np.argmin()

##  np.argmax () return  indices of max values along an axis
##  np.argmin () return  indices of min values along an axis


In [28]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
print(p1)
print(np.max(p1))
print(np.min(p1))

[12 14  7 79 32 45 28  4 17]
79
4


In [30]:
print(np.argmax(p1))
print(np.argmin(p1))

3
7


In [32]:
print(p1)
max_value = p1[np.argmax(p1)]
min_value = p1[np.argmin(p1)]
print("max_value is ", max_value)
print("min_value is ", min_value)

[12 14  7 79 32 45 28  4 17]
max_value is  79
min_value is  4


In [43]:
r = [[16,15,21],[15,16,8],[19,2,18],[9,12,13]]
p = np.array(r)
print(p)

[[16 15 21]
 [15 16  8]
 [19  2 18]
 [ 9 12 13]]


In [49]:
print(np.argmin(p,axis=0)) # column wise
print(np.argmin(p,axis=1)) # row wise
print(np.argmax(p,axis=0)) # column wise
print(np.argmin(p,axis=1)) # row wise


[3 2 1]
[1 2 1 0]
[2 1 0]
[1 2 1 0]


4) np.sort()

In [51]:
r1 = np.array([34,23,56,12,39])
print(r1)

[34 23 56 12 39]


In [53]:
r2 = np.sort(r1)   # ascending order
print(r2)
r2 = np.sort(r1)[::-1] # descending order
print(r2)

[12 23 34 39 56]
[56 39 34 23 12]


In [55]:
r1 = np.sort(r1)   # Default sorting
print(r1)

[12 23 34 39 56]


In [57]:
r3 = np.array([[11,21,18],[24,35,16],[7,14,3]])
print(r3)

[[11 21 18]
 [24 35 16]
 [ 7 14  3]]


In [59]:
r4 = np.sort(r3,axis=1)   # sort row wise
print(r4)
r5 = np.sort(r3,axis=0)  # sort column  wise
print(r5)


[[11 18 21]
 [16 24 35]
 [ 3  7 14]]
[[ 7 14  3]
 [11 21 16]
 [24 35 18]]


In [61]:
r6 = np.sort(r3) # default sort order is row wise
print(r6)

[[11 18 21]
 [16 24 35]
 [ 3  7 14]]


In [ ]:
5) np.where()

## return index position for the matching conditons


In [63]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
print(p1)

[12 14  7 79 32 45 28  4 17]


In [67]:
n2 = np.where(p1%3==0)
print(n2)
print(p1[np.where(p1%3==0)])

(array([0, 5], dtype=int64),)
[12 45]


In [69]:
print(p1)
print(np.where(p1<20))
print(p1[np.where(p1<20)])

[12 14  7 79 32 45 28  4 17]
(array([0, 1, 2, 7, 8], dtype=int64),)
[12 14  7  4 17]


### using np.where() with 3 parameters
indx is not return with this approach, rather array elements are modified according to the criteria

In [71]:
print(p1)
t1 = np.where(p1<20, p1+5, p1*2)        # if p1<20, then add 5 to those values, else multiply them by 2
print(t1)
t2 = np.where(p1%2==0, p1+10, p1-7)    # if p1%2==0, then add 10 to those values, else subtract 7 from them
print(t2)

[12 14  7 79 32 45 28  4 17]
[ 17  19  12 158  64  90  56   9  22]
[22 24  0 72 42 38 38 14 10]


In [75]:
w1 =np.array([[1,2,7],[3,4,-8],[5,6,0]])
print(w1)

[[ 1  2  7]
 [ 3  4 -8]
 [ 5  6  0]]


In [80]:
print(np.where(w1%2==0))
print(w1[np.where(w1%2==0)])

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 1, 2, 1, 2], dtype=int64))
[ 2  4 -8  6  0]


6) np.extract()

## directly returns the values on which condition are applied , using the second parameter as array name.

In [82]:
print(p1)

[12 14  7 79 32 45 28  4 17]


In [84]:
print(p1)
t1 = np.extract(p1>20,p1)
print(t1)
t2 = np.extract(p1%3!=0,p1)
print(t2)

[12 14  7 79 32 45 28  4 17]
[79 32 45 28]
[14  7 79 32 28  4 17]


In [86]:
w1 = np.array([[1,2,7],[3,4,8],[5,6,13]])
print(w1)

[[ 1  2  7]
 [ 3  4  8]
 [ 5  6 13]]


In [88]:
res = np.extract(w1%2==0,w1)
print(res)

[2 4 8 6]
