Array Indexing

In [2]:
import numpy as np

In [4]:
a = np.arange(32).reshape(2,4,4) # 3rd dim (grp) = 2, row = 4 , col = 4
print(a)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
int32
(2, 4, 4)
32
3


Note
1) top to bottom, we have positive row indexes. <br>
2) bottom to top, we have negative row indexes. <br>
3) left to right , we have positive column indexes. <br>
4) right to left , we have psoitive column indexes. <br>

In [10]:
print(a)
print(a[-2])      # grp-idx = -2
print(a[-1][-2])      # grp_idx = -1, row-idx = -2   
print(a[-1][-2][-3])      # grp-idx = -1, row-idx = -2 , col-idx = -3 
print(a[-1,2,2])         # grp-idx = -1, row-idx = 2, col-idx = 2
print(a[-2][0][-1])     # grp-idx = -2, row-idx = 0, col-idx = -1 
print(a[-1,3,2])       # grp-idx =1 , row-idx = 3, col-idx = 2

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 25 26 27]
25
26
3
30


3D Slicing 
Syntax 
s[start-grp : end-grp : step-grp, start-r : end-r: step-r : start-c : end-c : step-c]

In [13]:
print(a[1:,1:,2:])  # start-grp = 1, start-r =1 , start-c = 2
print(a[1:,:2,:2])   # start-grp = 1, end-r = 2, end-c = 2
print(a[0:1,3:,1:]) # start-grp = 0, end-grp = 1, start-r = 3, start-c = 1

[[[22 23]
  [26 27]
  [30 31]]]
[[[16 17]
  [20 21]]]
[[[13 14 15]]]


In [15]:
print(a[0:,1::2,:2])  # start-grp = 0, start-r = 1, step-r = 2, end-c = 2

[[[ 4  5]
  [12 13]]

 [[20 21]
  [28 29]]]


In [19]:
print(a[1:,1::2,:2])   # start-grp = 1, start-r = 1, step-r = 2, end-c =2
print(a[-1:,:,:])  #start-grp= -1
print(a[:-1,:,:])   # end-grp =-1

[[[20 21]
  [28 29]]]
[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [21]:
print(a[-2:,-2::-2,-1::-2]) # start-grp = -2, start-r = -2, step-r = -2, start-c = -1, step-c =-2
print(a[-2:,-1::-3,-1::-2]) # start-grp = -2, start-r = -1, step-r = -3, start-c =-1, step-c = -2

[[[11  9]
  [ 3  1]]

 [[27 25]
  [19 17]]]
[[[15 13]
  [ 3  1]]

 [[31 29]
  [19 17]]]


In [23]:
print(a[-2:,-1::-2,1:3]) # start-grp = -2, start-r = -1, step-r = -2, start-c = 1, end-c =3
print(a[:,::3,::2]) # step-r = 3, step-c = 2
print(a[-2::,-4::3,-3::2]) # start-grp = -2, start-r = -4, step-r = 3, start-c = -3, step-c = 2
print(a[-2::,-3:-1,1])  # start-grp = -2, start-r = -3, end-r = -1, start-c = 1

[[[13 14]
  [ 5  6]]

 [[29 30]
  [21 22]]]
[[[ 0  2]
  [12 14]]

 [[16 18]
  [28 30]]]
[[[ 1  3]
  [13 15]]

 [[17 19]
  [29 31]]]
[[ 5  9]
 [21 25]]


In [29]:
print(a[::-1,-2:-4:-1,-1::-2])  # step-grp = -1, start-r = -2, end-r = -4, step-r = -1, start-c = -1, step-c = -2
print(a[::-1,0::3,0::3]) 

[[[27 25]
  [23 21]]

 [[11  9]
  [ 7  5]]]
[[[16 19]
  [28 31]]

 [[ 0  3]
  [12 15]]]


In [35]:
print(a[[0,0,0,0],[1,0,2,3],[1,3,1,2]])
print(a[[0,1,0,1],[1,2,3,0],[2,0,1,2]])
print(a[[0,0,0,0,1],[0,1,2,3,2],[0,1,2,2,1]])

[ 5  3  9 14]
[ 6 24 13 18]
[ 0  5 10 14 25]
