1D  Indexing and slicing

Array Indexing

In [6]:
import numpy as np

In [10]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25])
print(a)
print(len(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
14
1
(14,)
int32
14


In [12]:
print(a)
print(a[0])
print(a[4])
print(a[8])
print(a[-2])
print(a[-7])
print(a[-5])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
12
16
20
24
19
21


1D Slicing Array
syntax :
s = np.array([10,20,30,40,50,60,70,90])
s[start:end:step]

In [18]:
print(a)
print(a[2:5]) # start = 2 , end = 5 , step = +1
print(a[3:])   # start = 3 , step = +1
print(a[ :6])  #  end = 6 , step = +1
print(a[-4:])  # start = -4, step = +1
print(a[:-6])  # end = -6 , step = +1
print(a[:])    # step = +1
print(a[::-1]) # reverse


[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16]
[15 16 17 18 19 20 21 22 23 24 25]
[12 13 14 15 16 17]
[22 23 24 25]
[12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [22]:
print(a)
print(a[1:8:2])  # start = 1 , end = 8 , step = +2 (1 + 2 = 3)  R to L  (end -1)
print(a[3:-7])  # start = 3 , end = -7 , step = +1    R to L (end -1)
print(a[3:-7:2])   # R to L (end -1)
print(a[-2:-8:-2])  # L to R  (end +1)
print(a[-2:3:-3])  # L to R  (end +1)
print(a[3:8:3])   # R to L  (end -1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[13 15 17 19]
[15 16 17 18]
[15 17]
[24 22 20]
[24 21 18]
[15 18]
