### 2D Indexing and slicing

# Array Indexing

In [8]:
import numpy as np

In [10]:
a = np.array([[12,15,18],[21,24,26]])
print(a)
print(a[0,1])  # row 0, cols 1
print(a[0][1])

[[12 15 18]
 [21 24 26]]
15
15


In [12]:
b = np.array([[31,32,33,34],[35,36,37,38],
              [39,40,41,42],[43,44,45,46]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
2
(4, 4)
16
int32


In [14]:
print(b)
print(b[2][0])   # row = 2 , cols = 0
print(b[-1][-2])
print(b[2][-3],b[-1][3])  # r = 2, c= -1,   r= -3, c = 3
print(b[1,2],b[0,3])
print(b[-3,-3],b[-2,-1])

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
39
45
40 46
37 34
36 42


# Array Slicing
# 2D slicing syntax
s[start_row : end_row : step_row : start_col : end_col : step_col]

In [16]:
s = np.array([[10,20,30,40],[50,60,70,80]])
print(s)
print(s[:2,1:])

[[10 20 30 40]
 [50 60 70 80]]
[[20 30 40]
 [60 70 80]]


In [18]:
print(b)
print("1\n",b[:-1])  # row = -1
print("2\n",b[:,-1])  # all cols are sliced, slicing  all rows from top to bottom till index - 2 
print("3\n",b[-2,:-2])  # start_row = -2, end_col = -2

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
1
 [[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]]
2
 [34 38 42 46]
3
 [39 40]


In [22]:
print(b)
print(b[1:,3:]) # Start-r = 1, step-r =1,  start-c = 3, step-c =+1

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
[[38]
 [42]
 [46]]


In [26]:
print(b)
print(b[-2:,:-1]) # start-r = -1, step-r = +1, end-c = -1, start-c = +1
print(b[1:,2:])  # start-r = 1,end-r = +1, start-c = 2, start-c = +1
print(b[:2,0:])  # end-r = 2, step-r = +1, start-c = 0, end-c = +1
print(b[::2,:1])   # step-r = +2, step-c= +1

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
[[39 40 41]
 [43 44 45]]
[[37 38]
 [41 42]
 [45 46]]
[[31 32 33 34]
 [35 36 37 38]]
[[31]
 [39]]


In [28]:
print(b[:2,::2]) # end-r = 2, step-r = +1, step-c = +2

[[31 33]
 [35 37]]


In [30]:
print(b[1::2,1::2]) # start-r = 1, step-r = 2, start-c = 1, step-c=2
print(b[0::2,0::3]) # start-r = 0, step-r = 2, start-c =0 , step-c = 3
print(b[-3::-1,-3]) # start-r = -3, step-r = -3, start-c = -3, step =+1

[[36 38]
 [44 46]]
[[31 34]
 [39 42]]
[36 32]


In [32]:
print(b[:2:-1,2::]) # end-r =2, step-r = -1, start-c = 2, step-c = +1
print(b[:1:-1,:3]) # end-r =1,step-r =-1, end-c = 3, step-c =+1
print(b[0::3,0::3]) # start-r = 0, step-r =3, start-c= 0, step-c = 3
print(b[-1::-3,-1::-3]) # start-r = -1, step-r = -3, start-c = -1, step-c = -3

[[45 46]]
[[43 44 45]
 [39 40 41]]
[[31 34]
 [43 46]]
[[46 43]
 [34 31]]


In [34]:
print(b[1:3,1:3]) # start-r = 1, end-r = 3, step-r =+1, start-c = 1, start-c = 3, step-c = +1
print(b[-2:-4:-1,-1::-3])  # start-r = -2, end-r = -4, step-r =-1, start-c = -1, step-c = -3
print(b[-2::-2,-2:-4:-1]) #  start-r = -2, step-r = -2, start-c = -2,end-c = -4, step-c = -1
print(b[-2::-2,-2:0:-1]) #  start-r = -2, step-r =-2, start-c = -2, end-c= 0,step-c = -1

[[36 37]
 [40 41]]
[[42 39]
 [38 35]]
[[41 40]
 [33 32]]
[[41 40]
 [33 32]]


## 2D Advance Indexing and slicing

In [36]:
print(b)
print(b[[0,1,2],[0,1,2]])
print(b[[0,1,2,3,0,3],[0,1,2,3,2,2]])
print(b[[0,1,2,3],[3,2,1,0]])
print(b[[1,2,-1,-2],[0,1,-2,-4]])

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
[31 36 41]
[31 36 41 46 33 45]
[34 37 40 43]
[35 40 45 39]
