In [2]:
import numpy as np

Solving linear equation with 2 unknown and 2 equations

find x and y from the following equations 
1. 2x + 3y = 20
2.  5x - 4y = 27

In [4]:
a = np.array([[2,3],[5,-4]])
b = np.array([20,27])
res = np.linalg.solve(a,b)
print(res)

[7. 2.]


Solving linear equation with 3 unknown and 3 equations

find x and y
1. 8x + 3y - 2z = 9
2. -4x + 7y + 5z = 15
3. 3x + 4y - 12z = 35

In [6]:
a = np.array([[8,3,-2],[-4,7,5],[3,4,-12]])
b = np.array([9,15,35])
x = np.linalg.solve(a,b)
print(x)

[-0.58226371  3.22870478 -1.98599767]


**Dot Product**
This is equaivalent to matrix multiplication

##**Rules for Dot product**

Array a(m,n) and b(p,q) are dot product compatible if n=p<br>
then the shape of the resultant shape of the array after dot product has been computed is (m,q)

In [8]:
a = np.array([[9,5,2,],[1,8,5],[3,1,6]])
print(a)
print(a.shape)

[[9 5 2]
 [1 8 5]
 [3 1 6]]
(3, 3)


In [10]:
b = np.array([[3,2],[1,4],[5,3]])
print(b)
print(b.shape)

[[3 2]
 [1 4]
 [5 3]]
(3, 2)


In [12]:
res1 = np.dot(a,b)  # (3,3) (3,2)
res2 = np.matmul(a,b)
print(res1)
print(res1.shape)
print(res2)
print(res2.shape)

[[42 44]
 [36 49]
 [40 28]]
(3, 2)
[[42 44]
 [36 49]
 [40 28]]
(3, 2)


##### Matrix Inverse

The Inverse of a square matrix A, is a matrix A-1 such that AA-1 = I
where I is the identity matrix and AA-1 is dot product between A and A-1

## Identity Matrix

A matrix where the primary diagonal elements are 1 and the remaining elements are 0

## Primary diagonal

In a square matrix elements starting from top left to the bottom right constitute primary diagonal elements

In [14]:
q = np.array([[2,3],[1,2]])
print(q)
print(q.shape)

[[2 3]
 [1 2]]
(2, 2)


In [16]:
q_inv = np.linalg.inv(q)
print(q_inv)

[[ 2. -3.]
 [-1.  2.]]


In [18]:
r1 = np.dot(q,q_inv)
print(r1)

[[1. 0.]
 [0. 1.]]


## Dterminant of a matrix

If A is a 2x2 matrix

In [20]:
w = np.array([[5,3],[2,4]])
print(w)
det = np.linalg.det(w)
print("Det of w is",round(det))

[[5 3]
 [2 4]]
Det of w is 14


## Trace

Trace is sum of primary diagonal elements

In [22]:
a = np.array([[3,6,2],[9,12,17],[22,18,15]])
print(a)
trace = np.trace(a)
print("Trace of a",trace)

[[ 3  6  2]
 [ 9 12 17]
 [22 18 15]]
Trace of a 30


## Eigen Values and Eigen Vector

1. Eigen values and eigen vectors are defined only for square matrices
2.  An eigen value of matrix A is a scalar (Lambda) such that the equation Au = ^u has a nontrivial solution.
3.  An eigen vector of matrix A is a nonzero v such that Au = ^u, for some scalar ^.
4.  Eigen vectors are by definition nonzero. Eigen values may be equal to zero.


Av = ^v

where
A = is the square matrix
^ = Eigen value
v = Eigen vectors

Av = ^Iv
Av - ^Iv = 0
v(A-^I) = 0

If v is non_zero, then det((A-^I)) = 0

In [ ]:
d = np.array([[7,4],[5,9]])
eig_val.eig_vec = np.linalg.eig(d)
print("Eigen values \n", eig_val)
print("Eigen vector\n", eig_val)