In [4]:
import numpy as np

Numpy Array 

In [64]:
# craeting numpy array using a list

n1 = np.array([3,4,4,6,7])
print(n1)
print(type(n1))

[3 4 4 6 7]
<class 'numpy.ndarray'>


In [12]:
# craeting numpy array using a list a tuple

a1 = [1,2,3,4,5]
a2 = (2,3,5)
s1 = np.array(a1)
s2 = np.array(a2)
print(s1)
print(type(s1))
print(s2)
print(type(s2))


[1 2 3 4 5]
<class 'numpy.ndarray'>
[2 3 5]
<class 'numpy.ndarray'>


In [22]:
# properties or attributes

s0 = np.array(15)   # scaler
print(s0)
print("dtype :", s0.dtype)   # datatype
print("size :", s0.size)  # number of elements
print("shape :",s0.shape)  # ()
print("ndim :",s0.ndim)  # 0


15
dtype : int32
size : 1
shape : ()
ndim : 0


In [24]:
s0 = np.array([2])   # scaler
print(s0)
print("dtype :", s0.dtype)   # datatype
print("size :", s0.size)  # number of elements
print("shape :",s0.shape)  # (1,)
print("ndim :",s0.ndim)  # 1



[2]
dtype : int32
size : 1
shape : (1,)
ndim : 1


In [26]:
s0 = np.array([2,3,4,5,6,6,7])   # scaler
print(s0)
print("dtype :", s0.dtype)   # datatype
print("size :", s0.size)  
print("shape :",s0.shape)  
print("ndim :",s0.ndim)  

[2 3 4 5 6 6 7]
dtype : int32
size : 7
shape : (7,)
ndim : 1


In [30]:
r = [[23,67,45],[56,99,85]]
print(r)

s1 = np.array(r)   
print(s1)
print("dtype :", s1.dtype)   # int32
print("size :", s1.size)   # 6 
print("shape :",s1.shape)  # 2 rows and 3 columns
print("ndim :",s1.ndim)  # 2

[[23, 67, 45], [56, 99, 85]]
[[23 67 45]
 [56 99 85]]
dtype : int32
size : 6
shape : (2, 3)
ndim : 2


In [34]:
s1 = np.array([[[1,2,3],[4,5,6]],[[6,7,9],[9,5,10]]])   
print(s1)
print("dtype :", s1.dtype)   # int32
print("size :", s1.size)   # 12
print("shape :",s1.shape)  # 2 group, 2 rows and 3 columns
print("ndim :",s1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  9]
  [ 9  5 10]]]
dtype : int32
size : 12
shape : (2, 2, 3)
ndim : 3


Numpy Arange

In [38]:
d1 = np.arange(10,20) # start = 10 , end = 20 , step =m +1 ...like range function
print(d1)
print("dtype :", d1.dtype)   # int32
print("size :", d1.size)   # 10
print("shape :",d1.shape)  # 10,
print("ndim :",d1.ndim) # 1

[10 11 12 13 14 15 16 17 18 19]
dtype : int32
size : 10
shape : (10,)
ndim : 1


d2 = np.arange(5,25,4) # start = 5, end = 25 , step = +4
print(d2)
d3 = np.arange(30,10,-5) # start = 30, end = 10 , step = -5
print(d3)

Numppy Zeros - Generate an array of zeros

In [46]:
w1 = np.zeros((3,4))   # 3rows and 4 cols
print(w1)
print("dtype :", w1.dtype)   # float64
print("size :", w1.size)   # 12
print("shape :",w1.shape)  # 3,4
print("ndim :",w1.ndim) # 2


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dtype : float64
size : 12
shape : (3, 4)
ndim : 2


In [48]:
w2 = np.zeros([4,2], dtype = "int")
print(w2)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [50]:
w2 = np.zeros((7), dtype = "int")
print(w2)
print("dtype :", w2.dtype)   # int32
print("size :", w2.size)   # 7
print("shape :",w2.shape)  # 7,
print("ndim :",w2.ndim) # 1


[0 0 0 0 0 0 0]
dtype : int32
size : 7
shape : (7,)
ndim : 1


Numpy ones - genrate an array of ones

In [5]:
G1 = np.ones((4,5), dtype = "int")
print(G1)
print("dtype :", G1.dtype)   # int32
print("size :", G1.size)   # 20
print("shape :",G1.shape)  # 4,5
print("ndim :",G1.ndim) # 2


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
dtype : int32
size : 20
shape : (4, 5)
ndim : 2


In [6]:
G2 = np.ones((2,3), dtype = "float")
print(G2)

[[1. 1. 1.]
 [1. 1. 1.]]


Reshape() and shape property
array can be reshaped into its products of its factors

In [66]:
b1 = np.array([2,3,3,5,6,3,8,2,9,4,8,10])
print(b1)
print("dtype :", b1.dtype)   # int32
print("size :", b1.size)   # 12
print("shape :",b1.shape)  # 12,
print("ndim :",b1.ndim) # 1
# factors of 12 - 1,2,3,4,6,12
# pairs = (3,4)(4,3)(6,2)(2,6)(12,1)(1,12)_

[ 2  3  3  5  6  3  8  2  9  4  8 10]
dtype : int32
size : 12
shape : (12,)
ndim : 1


In [70]:
b1 = np.array([2,3,3,5,6,3,8,2,9,4,8,10]).reshape(3,4)  # rows 3 and cols 4
print(b1)
print("dtype :", b1.dtype)   # int32
print("size :", b1.size)   # 12
print("shape :",b1.shape)  # 3,4
print("ndim :",b1.ndim) # 2

[[ 2  3  3  5]
 [ 6  3  8  2]
 [ 9  4  8 10]]
dtype : int32
size : 12
shape : (3, 4)
ndim : 2


In [80]:
print(b1.reshape(2,6))

[[ 2  3  3  5  6  3]
 [ 8  2  9  4  8 10]]


In [82]:
print(b1)
print(b1.shape)

[[ 2  3  3  5]
 [ 6  3  8  2]
 [ 9  4  8 10]]
(3, 4)


In [84]:
b2 = np.arange(1,19).reshape(6,3)
print(b2)
print(b2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)


In [88]:
b2.reshape(2,3,3)  # 3rd dim 3 rows 3 cols

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [94]:
print(b2.shape)

(6, 3)


In [98]:
h1 = b2.reshape(9,2)
print(h1)
print(h1.shape)
print(b2.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]
(9, 2)
(6, 3)


In [100]:
# reshape an array after its creation

b2.shape = (3,2,3)
print(b2)
print(b2.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)


In [103]:
b2.shape = (3,3,2)
print(b2)
print(b2.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)


In [105]:
z1 = np.arange(2,14).reshape(3,4,1)
print(z1)
print(z1.size)
print(z1.shape)

[[[ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]]]
12
(3, 4, 1)
