In [1]:
import numpy as np

Data type of numpy array is same throughout the array.
Elements in a numpy array are homogenous in nature

In [3]:
a1 = np.array([3,4,5.7,6])
print(a1)
print(a1.dtype)

[3.  4.  5.7 6. ]
float64


In [7]:
a2 = np.array(["Hello",3,4,5.7,6])
print(a2)
print(type(a2))
print(a2.dtype)

['Hello' '3' '4' '5.7' '6']
<class 'numpy.ndarray'>
<U32


Numpy Broadcasting

In [9]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
print('a',a)
print('b',b)
r1 = a * b  # elements wise multiplication
print(r1)

a [1. 2. 3.]
b [2. 2. 2.]
[2. 4. 6.]


In [13]:
a = np.array([3,4,5,6])
b = np.array(2)
print('a',a, 'Dim', a.ndim)
print('b',b, 'Dim', b.ndim)
r1 = a * b  # elements wise multiplication
print(r1)

a [3 4 5 6] Dim 1
b 2 Dim 0
[ 6  8 10 12]


Broadcasting Rules :
1. they are equal , or
2. one of them is 1

In [15]:
a = np.array([[1,2,3],[4,5,6]])   # ndim = 2
b = np.array(5)    # scaler , ndim = 0
print('a\n',a)
print('b',b)
print('a*b\n',a*b)

a
 [[1 2 3]
 [4 5 6]]
b 5
a*b
 [[ 5 10 15]
 [20 25 30]]


In [17]:
a = np.array([[1,2,3],[4,5,6]])   # ndim = 2
b = np.array([-1,0,1])    # scaler , ndim = 1
print('a\n',a, 'Dim', a.ndim)
print('b',b, 'Dim', b.ndim)
print('a*b\n',a*b)

a
 [[1 2 3]
 [4 5 6]] Dim 2
b [-1  0  1] Dim 1
a*b
 [[-1  0  3]
 [-4  0  6]]


In [23]:
a = np.array([[1,2,3],[4,5,6]])   # ndim = 2
b = np.array([[5,-4,2],[-2,3,-1]])    # scaler , ndim = 1
print('a\n',a, 'Dim :', a.ndim, ',Shape :', a.shape)
print('b',b, 'Dim :', b.ndim, 'Shape :', b.shape)
print('a*b\n',a*b)

a
 [[1 2 3]
 [4 5 6]] Dim : 2 ,Shape : (2, 3)
b [[ 5 -4  2]
 [-2  3 -1]] Dim : 2 Shape : (2, 3)
a*b
 [[ 5 -8  6]
 [-8 15 -6]]


np.linspace()
Generates linerarly space elements

In [31]:
z1 = np.linspace(2,10,5) # returing 5 linearly space elements between 2 and 10
print(z1)
z2 = np.linspace(2,10,3, dtype = 'int') # returing 3 linearly space elements between 2 and 10
print(z2)
s1 = np.linspace(5,20,7) # returing 7 linearly space elements between 5 and 20
print(s1)
s1 = np.linspace(5,20,7, dtype = int) # returing 7 linearly space elements between 5 and 20
print(s1)


[ 2.  4.  6.  8. 10.]
[ 2  6 10]
[ 5.   7.5 10.  12.5 15.  17.5 20. ]
[ 5  7 10 12 15 17 20]


In [35]:
z3 = np.linspace(2,20) # start =2, end = 20, defaul num = 50
print(z3)
print(type(z3))
print(len(z3))  # default length

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]
<class 'numpy.ndarray'>
50


In [37]:
w = np.linspace(5,20,7,retstep = True) # display distance of them
print(w)

(array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ]), 2.5)


Views vs copy
copy()
view()

In [39]:
a1 = np.array([1,2,3,4,5])
x = a1.copy()
print('a1\n', a1)
print('x\n', x)

a1 [0] = 50
print('a1\n', a1)
print('x\n', x)



a1
 [1 2 3 4 5]
x
 [1 2 3 4 5]
a1
 [50  2  3  4  5]
x
 [1 2 3 4 5]


In [41]:
a2 = np.array([1,2,3,4,5])
y = a2.view()
print('a2\n', a2)
print('y\n', y)

a2 [0] = 50
print('a2\n', a2)
print('y\n', y)


a2
 [1 2 3 4 5]
y
 [1 2 3 4 5]
a2
 [50  2  3  4  5]
y
 [50  2  3  4  5]


Numpy Random Numbers

np.random.random()
return random float in the half open interval [0.0,1.0]

a1 = np.random.random(5) # return 5 random nos betw 0 to 1
print(a1)
a2 = np.random.random((3,4))
print(a2)

np.random.randint(low,high,size)
return random integers from low (inclusive) to high (exclusive)
low < high

In [53]:
a3 = np.random.randint(3,15,4)
print(a3)
a4 = np.random.randint(50,100,8)
print(a4)
# a5 = np.random.randint(20,5,4) # error , low<high
# print(a5)

[ 9 11  7  8]
[55 80 89 52 69 89 99 78]


In [55]:
a5 = np.random.randint(10,50,(3,4))
print(a5)
# return a np array of shape (3,4) with random elements
# in the range (10,50)

[[21 40 26 18]
 [36 34 39 21]
 [27 11 46 18]]


np.random.rand()
generates random values between (0,1) in the given shape

In [59]:
w1 = np.random.rand(5)
print(w1)
w2 = np.random.rand(4,2)
print(w2)
# w3 = np.random.rand((4,2))
# print(w3)

[0.20772128 0.50739891 0.81736181 0.8864526  0.38899774]
[[0.94514457 0.33130538]
 [0.57697784 0.46444911]
 [0.81734617 0.56314784]
 [0.79785748 0.75001182]]


 np.random.choice
 generates a random sample from a given 1 - D array

In [61]:
f1 = np.random.choice([3,9,15,6,7,8], size = 4)
print(f1)

[ 8 15  8  9]


In [63]:
f2 = np.random.choice([3,9,15,6,7,8,13,15,12,11,10], size = 7)
print(f2)

[ 3  6  8 12  9 11  3]
